openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact Book API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    Це API для управління контактами користувачів.
    Воно підтримує авторизацію через JWT та CRUD-операції над контактами.

tags:
  - name: Contacts
    description: Операції з контактами

servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-64dr.onrender.com

paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml

  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml

  /auth/register:
    $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    $ref: ../swagger/paths/auth/refresh.yaml
  /auth/send-reset-email:
    $ref: ../swagger/paths/auth/send-reset-email.yaml
  /auth/reset-password:
    $ref: ../swagger/paths/auth/reset-pwd.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Contact:
      $ref: ../swagger/components/schemas/contact.yaml


